apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.authPostgres.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.authPostgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.authPostgres.db }}
            - name: POSTGRES_USER
              value: {{ .Values.authPostgres.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: auth-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: auth-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: auth-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
