apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  auth-password: {{ .Values.secrets.authPassword | quote }}
  facturacion-password: {{ .Values.secrets.facturacionPassword | quote }}
  document-password: {{ .Values.secrets.documentPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
